### ISSUE TITLE
RECONNECT

### ISSUE THREAD

**Issue by parsibox** [linxGnu/gosmpp#104]
HI
HOW CAN WE RECONNECT?
i need to detect now it is disconnected and reconnect again and send sms again
i want create a log on every disconnect and every reconnect
please help me

**Comment by tahseenjamal** [comment]
```
conn = tranceiver.Bind()
// after connection binding is done, below code in go routine would consistent check if connection is up or down
go func() {
     for conn_instance := range conn {
          fmt.Println(conn_instance.Status())
    }
}()
```
You can log it into a file or push it into elastic for visualization

**Comment by linxGnu** [comment]
@parsibox 

I am sorry for late reply due to personal matter. The latest version auto detect the event when connection broken or when closed on purpose.

You could use following hooks for your purpose:
https://github.com/linxGnu/gosmpp/blob/ca54e3b2d6c38f7636594d46da151793c7550eec/pkg.go#L48-L65
