### ISSUE TITLE
Window Size Parameter

### ISSUE THREAD

**Issue by tahseenjamal** [linxGnu/gosmpp#105]
Where do you have the window size parameter ?

**Comment by linxGnu** [comment]
@tahseenjamal 

what do you mean by window size parameter? could you please explain more

**Comment by goten4** [comment]
The window mechanism is not implemented in the lib, you have to code it.

**Comment by tahseenjamal** [comment]
@linxGnu It is more like how many messages can you send in parallel to SMPP without waiting for acknowledgement

if you set your windows parameter to 5 or 10 then your throughput increases

**Comment by linxGnu** [comment]
Thank you for clarifying. Just like @goten4 said, it's not implemented in the lib. There are reasons for it:

- Keep the lib as small/lean as possible
- Flexible for everyone to implement their own rate limiter
