### ISSUE TITLE
Error receiving

### ISSUE THREAD

**Issue by pietrodicaprio** [linxGnu/gosmpp#106]
Using the code from the example, after sending few SMSs I get `Receiving PDU/Network error: Not enough byte to read from buffer` but I don't understand where this buffer is set.\
Any suggestion?

**Comment by linxGnu** [comment]
@pietrodicaprio 

I am sorry for late response due to personal matter. Could you please give me stack trace of error. 

Basically, this error means the connection dropped and failed to read from conn.

**Comment by pietrodicaprio** [comment]
I'm not using the lib anymore as the provider (OVH) offers a different SMS package working via REST API and that is simpler for me.\
Anyway I didn't get any more detailed trace when getting that error.

**Comment by solaim** [comment]
same issue.
If CommandStatus not ESME_ROK, error: `Not enough byte to read from buffer`.
