### ISSUE TITLE
Codings split problems

### ISSUE THREAD

**Issue by lixianzhong25** [linxGnu/gosmpp#109]
I have contacted some SMPP service providers, they differentiate the length of segmentation based on encoding. I don't know if it's right or not.

- GSM7BITCoding  
SM_GSM_MSG_LEN：160 octetLimit : 154

- ASCIICoding 
SM_GSM_MSG_LEN：160 octetLimit : 154

- BINARY8BIT1Coding
SM_GSM_MSG_LEN：160 octetLimit : 154

- LATIN1Coding
SM_GSM_MSG_LEN：140 octetLimit : 134

- BINARY8BIT2Coding
SM_GSM_MSG_LEN：160 octetLimit : 154

- UCS2Coding
SM_GSM_MSG_LEN：70 octetLimit : 64

**Comment by goten4** [comment]
Sorry for the late response ... It's perfectly right. Here is an explanation :

[https://support.alarislabs.com/manual/latest/sms/how-to-calculate-the-allowed-n.html](https://support.alarislabs.com/manual/latest/sms/how-to-calculate-the-allowed-n.html)
