### ISSUE TITLE
Not enough byte to read from buffer

### ISSUE THREAD

**Issue by solaim** [linxGnu/gosmpp#112]
If CommandStatus not ESME_ROK, error: `Not enough byte to read from buffer`. And at server error occurred on connection`[::1]:62893, connection reset by peer\n`

same issue list
```
https://github.com/linxGnu/gosmpp/issues/106
https://github.com/linxGnu/gosmpp/pull/78
```

**Comment by linxGnu** [comment]
@solaim please try to enable enquire_link. This way, connection are kept alive.

**Comment by solaim** [comment]
I try to dig code:
```
type SubmitSMResp struct {
	base
	MessageID string
}
```

```
// Marshal implements PDU interface.
func (c *SubmitSMResp) Marshal(b *ByteBuffer) {
	c.base.marshal(b, func(b *ByteBuffer) {
		b.Grow(len(c.MessageID) + 1)

		_ = b.WriteCString(c.MessageID)
	})
}
```

```
// Unmarshal implements PDU interface.
func (c *SubmitSMResp) Unmarshal(b *ByteBuffer) error {
	return c.base.unmarshal(b, func(b *ByteBuffer) (err error) {
		if c.CommandStatus == data.ESME_ROK {
			c.MessageID, err = b.ReadCString()
		}
		return
	})
}
```

what will happen when CommandStatus not ESME_ROK, MessageID is empty string, but In Marshal function, just 
```
b.Grow(len(c.MessageID) + 1)

_ = b.WriteCString(c.MessageID)
```

maybe this is more better:
```
if len(c.MessageID) > 0 {
      b.Grow(len(c.MessageID) + 1)

      _ = b.WriteCString(c.MessageID)
}
```

**Comment by linxGnu** [comment]
@solaim good finding, I am making a fix here: https://github.com/linxGnu/gosmpp/pull/113
PTAL

**Comment by solaim** [comment]
LGTM

**Comment by linxGnu** [comment]
@solaim Thank you so much. I released a new version which includes above PR.

Please feel free to close this issue.
