### ISSUE TITLE
deliver sm resp

### ISSUE THREAD

**Issue by parsibox** [linxGnu/gosmpp#114]
hi
on deliver sm when we get a packet this lib send a response that is not true
response is like this image
how can send 0x00000000 instead of 0x00000094 ?
![image](https://github.com/linxGnu/gosmpp/assets/12513476/b4e25599-85dd-43de-9a4c-0b8f370334ed)
![image](https://github.com/linxGnu/gosmpp/assets/12513476/fb571ac4-3c15-4dc9-9d5d-895b0e110864)

**Comment by laduchesneau** [comment]
I dont think its gosmpp that is returning those errors. The default value for GetResponse is ESME_ROK (0). Before release v0.1.8, the library always responded with a ESME_ROK in all cases.

With v0.1.8, you can now pass the OnAllPDU setting and decide what you value you want to return.  Check the [transcceiver_with_manual_response](https://github.com/linxGnu/gosmpp/blob/master/example/transcceiver_with_manual_response/main.go) code to show you how you can use it.

**Comment by parsibox** [comment]
i was captured network and see that log sent from smpp client that only smpp client was gosmpp on this server
i was change it to manual response but i want to understand that responses sent from which part of gosmpp code

**Comment by laduchesneau** [comment]
The code that automatically respond is in [receivable.go](https://github.com/linxGnu/gosmpp/blob/07a919052b71e8c063efea7534a03cdad0e34d32/receivable.go#L108). Notice that on line [138](https://github.com/linxGnu/gosmpp/blob/07a919052b71e8c063efea7534a03cdad0e34d32/receivable.go#L108), it just calls GetResponse. If you follow the code, you will see that [NewDeliverSMResp](https://github.com/linxGnu/gosmpp/blob/07a919052b71e8c063efea7534a03cdad0e34d32/pdu/DeliverSMResp.go#L14) is called and initiate a new base header with default values, including CommandStatus being set to 0 (ESME_ROK).

Hope this helps.
