### ISSUE TITLE
BIND_RESP not return

### ISSUE THREAD

**Issue by parsibox** [linxGnu/gosmpp#115]
hi
when i use tx or rx for bind i did not receive BIND_RECEIVER_RESP or  BIND_TRANSCEIVER_RESP or BIND_TRANSMITTER_RESP
i want to get this log
please help me to find it

**Comment by laduchesneau** [comment]
There is no log, you need to implement it. When you call  [NewSession](https://github.com/linxGnu/gosmpp/blob/07a919052b71e8c063efea7534a03cdad0e34d32/session.go#L32), it returns a session and/or a error. The error should contains the information you are looking for.
