### ISSUE TITLE
Pdu Event handler does not fire for non OK PDUs

### ISSUE THREAD

**Issue by foxthedream** [linxGnu/gosmpp#117]
I have been testing with this library and purposefully sending to an SMSC using an unsupported encoding. The SMSC is sending back submit_sm_resp with submit_sm fail status. At no point is an event handler invoked. I have tried both OnAllPdu and OnPdu. Instead I see the connection being closed and a rebind happen. 

I need to intercept that exception so that I can log it. Am I missing something?

**Comment by laduchesneau** [comment]
You should get a call on the [OnClosed](https://github.com/linxGnu/gosmpp/blob/master/pkg.go#L67) func when the bind is closed, if unbind is sent from the SMSC.

The submit_sm_resp should be sent to [OnPdu](https://github.com/linxGnu/gosmpp/blob/master/pkg.go#L54) or [OnAllPdu](https://github.com/linxGnu/gosmpp/blob/master/pkg.go#L73).

**Comment by foxthedream** [comment]
Hi

I am getting a call on the OnClosed func. That's fine.
But I am not getting a call on either OnPdu or OnAllPdu when the submit_sm_resp from the SMSC contains a non ESME_ROK command_status. 

Also, I would argue that closing the bind on submit_sm_resp with a non ESME_ROK is the incorrect behaviour. If you submit with an invalid dest address or source address or some other issue then when the submit_sm_resp comes back in the bind gets closed. This is terrible for performance of the bind, the bind can be closed by the implementor.

**Comment by foxthedream** [comment]
The SMPP v3.4 spec does mention in the notes.
_The submit_sm_resp PDU Body is not returned if the command_status field contains a non-zero value._
The change you are referencing to not expect a message_id field I believe is correct.

**Comment by linxGnu** [comment]
Hi, could you please check if your issue still remains with latest v0.1.9.

Big kudos to @laduchesneau for great investigation and patch

**Comment by foxthedream** [comment]
Hi

I have pulled the latest and confirm it is working as expected.

Regards,
