### ISSUE TITLE
multipart message with our udh

### ISSUE THREAD

**Issue by parsibox** [linxGnu/gosmpp#122]
hi
i want to send multipart message with our udh 
i tried someway but i can not receive udh in my server.
 i do not want use split method
please help me
for example i test this code
```
	_ = submitSM.Message.SetLongMessageWithEnc(msg, data.GSM7BIT)
	submitSM.Message.SetUDH(pdu.UDH{pdu.NewIEConcatMessage(2, 1, 254)})

```

**Comment by goten4** [comment]
Don't forget to set ESM Class : 

```
submitSM.EsmClass = data.SM_UDH_GSM
```
