### ISSUE TITLE
Long messages in the latest version

### ISSUE THREAD

**Issue by tahseenjamal** [linxGnu/gosmpp#125]
Once I call 

```
_ = submitSM.Message.SetMessageWithEncoding("Hello World how are you there, this is a test message that has to be checked whether this is going to be a message or a short message and if encoding is required or not ", data.GSM7BIT)

submitSM.Split()
```

This returns two arrays, does that mean I have to submit each of them one by one to 
`trans.Transceiver().Submit( SubmitSM )`

**Comment by goten4** [comment]
That's right, the `Split()` will split the PDU in as many parts as necessary depending on the encoding you choose.
You just have to submit each PDU, like you said.

**Comment by tahseenjamal** [comment]
So my next question is that if running in an endless loop
```
c := make(chan pdu.SubmitSM)

for {
    trans.Transceiver().Submit( <-c )
}

```

And now I have exposed an API to accept messages. And let us say concurrently 100 long messages are submitted on the API

Each API would internally create submitSM, check shouldSplit() and then call split() and then push into the channel

So the channel might have submitSM in a mix going to Submit() function of transceiver

Will this approach cause issue ? Is it required that the Transceiver receive all the split() one after another ? 

I don't think so but still want to confirm

**Comment by goten4** [comment]
Theoretically the protocol accepts this approach, but it may depends on the SMSC implementation.
If you want to ensure that the parts will be sent sequentially, you could do that instead : 

```
c := make(chan []*pdu.SubmitSM)

for {
    for _, p := range <-c {
        trans.Transceiver().Submit(p)
    }
}
```

If the SubmitSM have to be split, just put the result of the `Split()` method in the channel, if not, just put the single SubmitSM in a slice and put it in the channel.

**Comment by tahseenjamal** [comment]
@goten4  loved your approach. Outstanding approach

**Comment by tahseenjamal** [comment]
I checked the code and found that when the messages are split, each message udh has same reference number. And this reference number is uniquely created for each long message. Then segment number i is also put inside udHeader. i helps in knowing segment order concatenation chain 

Which means the SMSc is using a common reference number for all the segments along with sequence number i

This way out of hundreds of messages even for the same number, SMSc would know the segments of one long message along with what is their concatenation order



```
multiSM = append(multiSM, &ShortMessage{
			enc: c.enc,
			// message: we don't really care
			messageData:       seg,
			withoutDataCoding: c.withoutDataCoding,
			udHeader:          UDH{NewIEConcatMessage(uint8(len(segments)), uint8(i+1), uint8(ref))},
		})
```

**Comment by bluewithanas** [comment]
hey @tahseenjamal in this case how did you handled the callbacks (Submit_sm_resps and DLRS), because i recieve each event per segment and this piece of code returns  `found=false` even though i am splitting the message. 

```
totalParts, sequence, reference, found := pd.Message.UDH().GetConcatInfo()
			if found {
				if _, ok := concatenated[reference]; !ok {
					concatenated[reference] = make([]string, totalParts)
				}
				concatenated[reference][sequence-1] = message

			}
			if !found {
				log.Println(message) //events print just here. 
			} else if parts, ok := concatenated[reference]; ok && isConcatenatedDone(parts, totalParts) {
				log.Println(strings.Join(parts, ""), "LONG+MESSAGE CONCAT")
				delete(concatenated, reference)
			}
```


I am mapping and updating the status of the sms and i dont care about the segment i just need one. is it fine by practise to ignore the rest?
