### ISSUE TITLE
Relating submitted message with message id

### ISSUE THREAD

**Issue by tahseenjamal** [linxGnu/gosmpp#126]
When I submit a message, all I get to know if there was an error or not

If not then there would be submit response that I would receive via handler. 

In a multi threaded scenario, how would I know for which number and message that I submitted is related to which message ID ?

**Comment by laduchesneau** [comment]
Its up to the user to implement this.

I use a map and store the PDU SequenceNumber as the KeyType. When I receive a response, I just get the value with the resp sequence number. Something like this:
```map[int32]Request```

```
type Request struct{
    OrignalPDU *PDU
    SubmitTime  Time
    ....
}
```
I also use the map lenght as a Bind window.

Don't forget that Golang map is not thread safe, so you'll also need to manage your access .

**Comment by tahseenjamal** [comment]
How do you get the sequence number when you are submitting your message using transceiver ? Because it only returns error status or else nil

**Comment by laduchesneau** [comment]
You have access to the sequence number that will be used before you send the PDU on the connection.

When you create a PDU with its New function, like [NewSubmitSm()](https://github.com/linxGnu/gosmpp/blob/master/pdu/SubmitSM.go#L26), it calls [newbase()](https://github.com/linxGnu/gosmpp/blob/master/pdu/PDU.go#L54) and that calls [AssignSequenceNumber()](https://github.com/linxGnu/gosmpp/blob/master/pdu/PDUHeader.go#L58).

**Comment by tahseenjamal** [comment]
Ok this works for short message well. 

Also, I was testing with long message where Split is called

`submitSMs, err := submitSM.Split()`

There is only 1 item in the array, even when the message is 400 characters on

**Comment by bluewithanas** [comment]
hey @tahseenjamal how did you managed to set your custom sequence number? can we add our own custom number to the sequence number to submitSM PDU and receive the same on submitSMRESP and deliverSM?

**Comment by bluewithanas** [comment]
thanks! I can  manuallly add sequence number so it solves, the problem for mapping! 

but one thing, i see here is whole process is totally async and i find it quite difficult to move data around! My use case is i exposed an API upon which it triggers sends and hit submitSM command. 

now, all the PDU driven work is in handlePDU function  which is triggered when any `onPDU` receives something. 

How do i move my data let say a webhook URL coming from API  body inside the `handlePDU` function. i feel things are quite tightly coupled here.

**Comment by bluewithanas** [comment]
also @NitinHsharma are you aware if this is the case where for the same message , on DeliverSM delivery receipt, we dont get the same sequence number? i am getting a different one in the headers.

**Comment by tahseenjamal** [comment]
> hey @tahseenjamal how did you managed to set your custom sequence number? can we add our own custom number to the sequence number to submitSM PDU and receive the same on submitSMRESP and deliverSM?

@bluewithanas SubmitSM automatically generates the sequence number else you can call its methods call set sequence

**Comment by tahseenjamal** [comment]
[](https://github.com/tahseenjamal/smpp_client/blob/master/main.go)

You can go through the code that I wrote, in this you can see at the bottom, where the SubmitSM is prepared, I print sequence number. You can also call set sequence function of SubmitSM

also you can see the SubmitSMResp handler getting sequence number as well as messageid

and in delivery report you get messageid, you this way you can crack the puzzle of tracking the message life cycle

**Comment by bluewithanas** [comment]
thanks you @tahseenjamal
