### ISSUE TITLE
is there a way to set a custom uuid with a short message and receive the uuid in reply/delivered callbacks?

### ISSUE THREAD

**Issue by bluewithanas** [linxGnu/gosmpp#127]
The idea is to keep a mapping for the messages in our system using a uuid per message and map the lifecyle of each message and it's reply/ delivered / error callback received. If there's a way i can set a custom uuid in the headers or optional parameters i can easily parse the callbacks and get the uuid and maintain the mapping on my end.

**Comment by tahseenjamal** [comment]
Before submitting the message, you can check the sequence number of the SubmitSM
When you submit to transceiver, you get a call back of SubmitSM Resp in which you have sequence number and ack id of smpp
In the delivery receipt you have the ack id

So now you can relate. 

Basically you don't have to do any UUID part. The missing link can be sorted if you start using sequence number also as a reference

**Comment by bluewithanas** [comment]
thanks, @tahseenjamal i can link msg IDs now.
