### ISSUE TITLE
Setup addressRange for binding with SMSC

### ISSUE THREAD

**Issue by Hurtsich** [linxGnu/gosmpp#132]
Hello,

We're using the lib to connect to SMSC but there was no way to setup the address range parameter within the connector.
We saw that the bindRequest struct was responsible for it and we took the freedom to improve the way we instantiate the connector.
With this pull request you can see that on the Receiver and Transceiver, we can now modify the connector without breaking the public interface of the lib. Which can now be used to add the addressRange option.

https://github.com/linxGnu/gosmpp/pull/131

I'm available to discuss the matter on how to specify the address range :)

**Comment by linxGnu** [comment]
Hi @Hurtsich 
Thank you so much for making a great PR 💯 
I will close this issue here and release a new version.
