### ISSUE TITLE
connection is closing, can not send PDU to SMSC

### ISSUE THREAD

**Issue by parsibox** [linxGnu/gosmpp#135]
hi
dear after a period of time ( for example 1-2 day after bind ) we can not submit sms and we get error `connection is closing, can not send PDU to SMSC` but i create a tcp dump and see we are sending and receiving handshake but there is no log for submit_sm in tcp dump
i actually can not understand  what happend
![image](https://github.com/linxGnu/gosmpp/assets/12513476/52600de3-fe8b-4328-8d50-284c3b65803b)

**Comment by laduchesneau** [comment]
We will need more info to help you, the pcap doesnt show call flow, who is sending the enquire_link ?
Lets start with the basics:

-  What Bind type ?
- What PDU handler are you using, OnPDU or OnAllPDU ?

**Comment by parsibox** [comment]
enquire_link  is automatic
bind type is transmitter
PDU handler  is OnAllPDU

**Comment by laduchesneau** [comment]
How do you handle unbind request in OnAllPDU ?

**Comment by parsibox** [comment]
```go
OnPDU: PDUController(),
 
func PDUController() func(pdu2.PDU, bool) {
	return func(p pdu2.PDU, _ bool) {
		pduHeader := p.GetHeader()
		if pduHeader.CommandID.String() != "ENQUIRE_LINK_RESP" && pduHeader.CommandID.String() != "ENQUIRE_LINK" {
			file_logger_controller.AllReceivedPDUsController(map[string]interface{}{
				"CommandIDType":  pduHeader.CommandID.String(),
				"CommandLength":  pduHeader.CommandLength,
				"CommandStatus":  pduHeader.CommandStatus,
				"SequenceNumber": pduHeader.SequenceNumber,
			})
		}

		switch pd := p.(type) {
		case *pdu2.SubmitSMResp:
			SubmitResponseController(p)
		case *pdu2.GenericNack:
			//fmt.Println("GenericNack Received")
		case *pdu2.EnquireLinkResp:
			
		case *pdu2.BindRequest:
			BindRequestController(p)
		case *pdu2.BindResp:
			BindResponseController(p)
		case *pdu2.Unbind:
			UnbindController(p)
		case *pdu2.UnbindResp:
			UnbindResponseController(p)
		case *pdu2.DataSM:
			//fmt.Println("DataSM Received")
		case *pdu2.DeliverSM:
			DeliveryAndReceiveController(p)
			p.IsGNack()

		}

	}
}


func UnbindController(p pdu2.PDU) {
	switch pd := p.(type) {
	case *pdu2.Unbind:

		pduMap := map[string]interface{}{
			"Type":               "Unbind",
			"CommandIDType":      pd.CommandID.String(),
			"CommandLength":      pd.CommandLength,
			"CommandStatus":      pd.CommandStatus,
			"SequenceNumber":     pd.SequenceNumber,
			"OptionalParameters": pd.OptionalParameters,
			"DateTime":           time.Now().UTC().Add(time.Duration(time_zone_config.TimeZoneMinute) * time.Minute),
		}

		file_logger_controller.NewSessionSMSController(pduMap)

	}
}


```

**Comment by laduchesneau** [comment]
The code example provide is using OnPDU, not OnAllPDU. The difference is that the Unbind request from the SMSC is automatically responded too. This also means that if the bind get closed, the enquire_link should also stop. But you are saying the enquire_link continue working, just the other submits arent.

Both the loop for sending enquire_link and the submit use the same transmittable variable in transmitable.go . 
```
for {
		select {
		case <-ticker.C:
			eqp := pdu.NewEnquireLink()
			n, err := t.write(eqp)
			if t.check(eqp, n, err) {
				return
			}

		case p, ok := <-t.input:
			if !ok {
				return
			}

			if p != nil {
				n, err := t.write(p)
				if t.check(p, n, err) {
					return
				}
			}
		}
	}
```

Are you logging something from the OnClosed func call ? If yes, are you seeing any logs ?

**Comment by parsibox** [comment]
yes i receive disconnect from OnClosed  and i manually start create new session  but when new session start submit_sm not work or connect some times not work , some times hand shake not start
is there any limitation for create new session in your lib?
i think there is some problem in rebind manually  , we can not close old session correct

**Comment by laduchesneau** [comment]
> i manually start create new session

You dont need to start a new session ? Let the library reconnect for you.

But when you create the new session, do you assign it back to your Submit func ? I believe this is your issue....  Your function is still pointing to the old session.

**Comment by parsibox** [comment]
i check it but new session hanged on connect in your library code
i think something is in your lib
can you create a test for have reconnect manualy?

**Comment by laduchesneau** [comment]
If you provide a test that show your issue/failure, I would gladly try and help you resolve it.

If you need a new feature, feel free to submit a PR.
