### ISSUE TITLE
Reconnecting to SMPP Server

### ISSUE THREAD

**Issue by mohamadkenway** [linxGnu/gosmpp#137]
Hi 
how we can implement reconnect to smpp server due lost connection and etc ..
please guide us

**Comment by laduchesneau** [comment]
As per the comment for [NewSession](https://github.com/linxGnu/gosmpp/blob/3c44160054d3f0c9e4d009e97b188bfa5df5ef9c/session.go#L32) 

```
// `rebindingInterval` indicates duration that Session has to wait before rebinding again.
//
// Setting `rebindingInterval <= 0` will disable `auto-rebind` functionality.
```

All you need is a rebindingInterval greater than 0 and the library will handle reconnecting.
