### ISSUE TITLE
It's possible send flash sms?

### ISSUE THREAD

**Issue by xhit** [linxGnu/gosmpp#149]
How to send flash sms with this package? I need to create a custom encoding?

**Comment by laduchesneau** [comment]
What is a flash SMS  ?

This is a SMPP client library. You can connect to a SMPP server like an SMSC and send SMS via a submit_sm.

**Comment by xhit** [comment]
@laduchesneau this https://support.alarislabs.com/manual/latest/sms/data-coding-in-smpp.html

**Comment by laduchesneau** [comment]
Those are DCS values representing encoding. This library supports the most common ones but also supports custom encodings.

**Comment by xhit** [comment]
Thanks, solved with custom encoding
