### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by vasundhara785** [linxGnu/gosmpp#17]
Can u please provide example for smpp client connection handling all pdu...Earlier it was there in test folder now it has been removed..
Thanks

**Comment by linxGnu** [comment]
Hello @vasundhara785 could you please check it out at https://github.com/linxGnu/gosmpp/releases/tag/v0.1.3

There is source code for previous version. 

Fyi, we are building up 0.1.4 with lot of optimization and new concept which is easy to use.

**Comment by linxGnu** [comment]
And please also take a look at following closed issue: https://github.com/linxGnu/gosmpp/issues/4
