### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by itsursujit** [linxGnu/gosmpp#19]
I installed go package `go get -u github.com/linxGnu/gosmpp`

And used file https://github.com/linxGnu/gosmpp/blob/master/example/main.go

But running `go build` I'm getting following error:

```
main.go:10:2: case-insensitive import collision: "github.com/linxGnu/gosmpp/data" and "github.com/linxGnu/gosmpp/Data"
main.go:11:2: case-insensitive import collision: "github.com/linxGnu/gosmpp/pdu" and "github.com/linxGnu/gosmpp/PDU"
```

How would I fix it?

**Comment by linxGnu** [comment]
Hello @itsursujit 

I think go mod fetch old version of gosmpp and ignore RC version.

If you want to run the example, you could create a go.mod file to tell go which version you want. Then in go.mod, replace gosmpp version with hash value of commit.

The same approach applies to production.

Please tell me if you still get errors.

**Comment by itsursujit** [comment]
The latest commit I used is working fine.
Thank you!
