### ISSUE TITLE
Getting Error when trying to send one message

### ISSUE THREAD

**Issue by itsursujit** [linxGnu/gosmpp#22]
I'm trying to modify example/main.go to send one message instead of loop.

```
package main

import (
	"fmt"
	"log"
	"sync"
	"time"

	"github.com/linxGnu/gosmpp"
	"github.com/linxGnu/gosmpp/data"
	"github.com/linxGnu/gosmpp/pdu"
)


func main() {
	var wg sync.WaitGroup

	wg.Add(1)
	go sendingAndReceiveSMS(&wg)

	wg.Wait()
}

func sendingAndReceiveSMS(wg *sync.WaitGroup) {
	defer wg.Done()

	auth := gosmpp.Auth{
		SMSC:       "192.168.88.250:2775",
		SystemID:   "522241",
		Password:   "UUDHWB",
		SystemType: "",
	}

	trans, err := gosmpp.NewTransceiverSession(gosmpp.NonTLSDialer, auth, gosmpp.TransceiveSettings{
		EnquireLink: 5 * time.Second,

		OnSubmitError: func(p pdu.PDU, err error) {
			log.Fatal(err)
		},

		OnReceivingError: func(err error) {
			fmt.Println(err)
		},

		OnRebindingError: func(err error) {
			fmt.Println(err)
		},

		OnPDU: handlePDU(),

		OnClosed: func(state gosmpp.State) {
			fmt.Println(state)
		},
	}, 5*time.Second)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		_ = trans.Close()
	}()

	// sending SMS(s)
	if err = trans.Transceiver().Submit(newSubmitSM()); err != nil {
		log.Fatal(err)
	}
}

func handlePDU() func(pdu.PDU, bool) {
	return func(p pdu.PDU, responded bool) {
		switch pd := p.(type) {
		case *pdu.SubmitSMResp:
			fmt.Printf("SubmitSMResp:%+v\n", pd)

		case *pdu.GenerickNack:
			fmt.Println("GenericNack Received")

		case *pdu.EnquireLinkResp:
			fmt.Println("EnquireLinkResp Received")

		case *pdu.DataSM:
			fmt.Printf("DataSM:%+v\n", pd)

		case *pdu.DeliverSM:
			fmt.Printf("DeliverSM:%+v\n", pd)
			fmt.Println(pd.Message.GetMessage())
		}
	}
}

func newSubmitSM() *pdu.SubmitSM {
	// build up submitSM
	srcAddr := pdu.NewAddress()
	srcAddr.SetTon(5)
	srcAddr.SetNpi(0)
	_ = srcAddr.SetAddress("00" + "522241")

	destAddr := pdu.NewAddress()
	destAddr.SetTon(1)
	destAddr.SetNpi(1)
	_ = destAddr.SetAddress("99" + "522241")

	submitSM := pdu.NewSubmitSM().(*pdu.SubmitSM)
	submitSM.SourceAddr = srcAddr
	submitSM.DestAddr = destAddr
	_ = submitSM.Message.SetMessageWithEncoding("Đừng buồn thế dù ngoài kia vẫn mưa nghiễng rợi tý tỵ", data.UCS2)
	submitSM.ProtocolID = 0
	submitSM.RegisteredDelivery = 1
	submitSM.ReplaceIfPresentFlag = 0
	submitSM.EsmClass = 0

	return submitSM
}
```

But I'm getting error
`read tcp 192.168.88.248:52461->192.168.88.250:2775: use of closed network connection`

How would I fix it?
Also is there any example where I can connect to SMSC once and send as many messages to different numbers?
Actually I'm new to go and little knowledge of smpp.

**Comment by linxGnu** [comment]
@itsursujit sending sms (underlying) is async. This is thread safety enforcement due to the fact that smpp protocol is not multiplex capable.

You coud “sleep” before quiting. Another option is let me improve transaction graceful shutdown

**Comment by linxGnu** [comment]
@itsursujit Could you please try rc10 (latest commit). I have just improve graceful shutdown a bit. You won't see error due to sudden closing net.Conn.

Thank you very much for playing around with gosmpp.

**Comment by itsursujit** [comment]
Yes Now it's working without any issue.
How is the callback of the final status of a message is received? Is there any way I wait for callback of message either it's delivered or not?

**Comment by linxGnu** [comment]
@itsursujit I guess you could not and SHOULD not wait. 

There is no way to know when SMSC returns SubmitSMResp. Some SMSC misses the response.

**Comment by itsursujit** [comment]
I wonder how other SMPP Gateway like Jasmin SMS Gateway receives callback (DLR) from SMSC and sends callback to user defined callback URL

**Comment by linxGnu** [comment]
@itsursujit 
- You could dig deep into Smpp 3.4 Specification: https://smpp.org/SMPP_v3_4_Issue1_2.pdf
- For smpp framework, please also check out: https://github.com/OpenSmpp/opensmpp

I will close this. If you have any other problems, please don't hesitate to open issue.
