### ISSUE TITLE
How to set TON/NPI values in multiple destination addresses

### ISSUE THREAD

**Issue by qosimmax** [linxGnu/gosmpp#30]
Hi @linxGnu 
d1 := pdu.NewDestinationAddress()
 there is no functions   SetTon(), SetNpi()  
how can i set this  TON/NPI values?

**Comment by linxGnu** [comment]
Hello @qosimmax 
Thank you very much for your concern. Yes, its lacking of configurable option.

I have updated the interface a bit and let user inject `Address` directly. You could set ton/npi in `Address` and inject into DestinationAddress now.

Sample code:
```go
addr := NewAddress()
addr.SetAddress("my_number")
addr.SetTon()
addr.SetNpi()

d := NewDestinationAddress()
d.SetAddress(addr)
```

**Comment by qosimmax** [comment]
Thanks @linxGnu 👍

**Comment by linxGnu** [comment]
Thank you for the report. I will close the issue for now.
