### ISSUE TITLE
How to concatenated sms?

### ISSUE THREAD

**Issue by septs** [linxGnu/gosmpp#33]
https://en.wikipedia.org/wiki/Concatenated_SMS

**Comment by septs** [comment]
https://smpp.io/concatenated-messages/

please export `UDH` info
https://github.com/linxGnu/gosmpp/blob/297995d40f7e6fc4d8926092a7e32f63e334f089/pdu/ShortMessage.go#L14-L22

and provide an example of concatenated sms 

thanks.

**Comment by septs** [comment]
@linxGnu Hope to provide a typical Concatenated SMS example for other user.

**Comment by linxGnu** [comment]
@septs At the moment, I don't have much time to provide full example. I will try soon.
So, if possible, it's great with your help.

**Comment by septs** [comment]
code:
```go
log.Println("UDH: ", pd.Message.UDH())
log.Println(pd.Message.UDH().GetConcatInfo())
```

logging:
```txt
2020/09/16 16:51:42 UDH:  [{0 [0 3 1 2 2]}]
2020/09/16 16:51:42 0 0 0 false
```

**Comment by septs** [comment]
https://github.com/linxGnu/gosmpp/blob/d4210d5883eee7ff19e50ed6edd9811ca84573e4/pdu/UDH.go#L98

The length check is `3`, actual length is `5`
