### ISSUE TITLE
Is it possible to detect sms encoding?

### ISSUE THREAD

**Issue by itsursujit** [linxGnu/gosmpp#39]
Thank you for this great library.
I am trying to implement this library along with REST.

User might send any text message with different message encoding.

Is it possible to detect the encoding?

By detecting the encoding, I wanted to clean the message content.

Some time the message content contains invisible empty characters which will change message encoding and thus message parts (length) might increase.

**Comment by septs** [comment]
https://github.com/linxGnu/gosmpp/blob/cc603b5cc822dcd18a9d1e72b65158f773be5db5/data/utils.go#L7-L14

@linhduonggnu did not implement, auto detect best encoding.

**Comment by linxGnu** [comment]
Yeah, for MO, it had been done with pdu header automatically. You could check GetMessage API for detail.

Please tell me if my answer not make sense to you. Thank you :)

**Comment by itsursujit** [comment]
@linxGnu  I went through this file: https://github.com/linxGnu/gosmpp/blob/d4210d5883eee7ff19e50ed6edd9811ca84573e4/pdu/ShortMessage.go

In GetMessage API, you are checking for Encoding that's already assigned from other APIs

The APIs like 

```go
// NewShortMessage returns new ShortMessage.
func NewShortMessage(message string) (s ShortMessage, err error) {
	err = s.SetMessageWithEncoding(message, data.GSM7BIT)
	return
}

// NewShortMessageWithEncoding returns new ShortMessage with predefined encoding.
func NewShortMessageWithEncoding(message string, enc data.Encoding) (s ShortMessage, err error) {
	err = s.SetMessageWithEncoding(message, enc)
	return
}

// NewLongMessage return long message splitted into multiple short message
func NewLongMessage(message string) (s []*ShortMessage, err error) {
	return NewLongMessageWithEncoding(message, data.GSM7BIT)
}

// NewLongMessage return long message splitted into multiple short message with encoding of choice
func NewLongMessageWithEncoding(message string, enc data.Encoding) (s []*ShortMessage, err error) {
	sm := &ShortMessage{
		message: message,
		enc:     enc,
	}
	return sm.Split()
}

// SetMessageWithEncoding set message with encoding.
func (c *ShortMessage) SetMessageWithEncoding(message string, enc data.Encoding) (err error) {
	if c.messageData, err = enc.Encode(message); err == nil {
		if len(c.messageData) > data.SM_MSG_LEN {
			err = errors.ErrShortMessageLengthTooLarge
		} else {
			c.message = message
			c.enc = enc
		}
	}
	return
}

// SetLongMessageWithEnc set ShortMessage with message longer than  256 bytes
// callers are expected to call Split() after this
func (c *ShortMessage) SetLongMessageWithEnc(message string, enc data.Encoding) (err error) {
	c.message = message
	c.enc = enc
	return
}
```
 you are explicitly defining the Encoding but not parsing the message content to identify the encoding.

**Comment by linxGnu** [comment]
@itsursujit Do you mean: Identify encoding of `go std string type`?

**Comment by itsursujit** [comment]
@linxGnu yes.

For e.g.

`This is example test` is GSM
`:package: package (with Emojis) This is example test` is UCS2

I mean to identify above string character encoding

**Comment by linxGnu** [comment]
@itsursujit I am afraid that it's hard to have a perfect encoding detection at the moment. I still think you should pass Encoding type around services when working with multi enc :(

**Comment by itsursujit** [comment]
@linxGnu I agree it's hard to get perfect encoding detection. At least we could implement detecting GSM 7-bit, or unicode or UCS2.

There's some library that is already detecting GSM 7-bit or unicode and sanitizing them.

https://github.com/instasent/sms-counter-php/blob/master/SMSCounter.php
https://github.com/danxexe/sms-counter/blob/master/sms_counter.js
https://github.com/SiddhantAgarwal/GoSMSLengthFinder/blob/master/sms_length.go

In worst case, we could strict client application. I've faced the scenario where user would send any type of message. 
There might be cases where user unknowingly add empty width characters
https://emptycharacter.com/

Causes issues for them.

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/93857615-72b2f180-fced-11ea-9fdf-bb39bf8adbed.png)

I did this in another project

**Comment by itsursujit** [comment]
This seems great.. @septs is it possible to share?

**Comment by septs** [comment]
@itsursujit I am not sure if I fully understand https://unicode.org, Sorry.

**Comment by itsursujit** [comment]
@septs We don't need all unicode characters...
For SMS Sending, If we could identify GSM, Unicode 8-Bit, 16-Bit or UCS2... Then everything should be fine related to SMS content.

Looking forward for above function. It will help a lot on detecting encoding

**Comment by septs** [comment]
https://github.com/linxGnu/gosmpp/pull/36#issuecomment-693346005
https://github.com/linxGnu/gosmpp/pull/36#pullrequestreview-492320765
https://github.com/linxGnu/gosmpp/issues/40#issuecomment-696064272
https://github.com/linxGnu/gosmpp/pull/41#issuecomment-695951445

This is a big revision, will not be accept

So I will not submit the next PR for this project, Sorry.

**Comment by itsursujit** [comment]
Maybe on this? https://github.com/itsursujit/gosmpp

**Comment by septs** [comment]
@itsursujit 

if you can provide **USSD over SMPP** detailed method. (best is capture packet)

i am happy to share my repo

**Comment by itsursujit** [comment]
@septs I'm learning SMPP. USSD over SMPP is out of my understanding :)

**Comment by itsursujit** [comment]
@septs There's something I found for node
https://github.com/jarmex/RVD-Node

**Comment by septs** [comment]
@itsursujit seen it already, but no help, thanks.

**Comment by septs** [comment]
```go
package coding

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

//goland:noinspection SpellCheckingInspection
var multipartList = [][]string{
	{ // 7 Bits
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent molestie eros ut ex dapibus sollicitudin in ut eros. Pellentesque venenatis vitae est e",
		"u porttitor. Nullam facilisis euismod felis, consectetur vehicula lorem aliquet at. Sed sit amet auctor lorem. Pellentesque euismod, orci non iaculis ull",
		"amcorper, massa ligula commodo sem, ac dictum lorem nulla vel tortor. Nam viverra urna justo, vitae porttitor purus auctor vel. Etiam pellentesque justo ",
		"quis ante fringilla, eu suscipit massa volutpat. In nec bibendum neque. Nam ex metus, venenatis et libero finibus, tristique pharetra nulla. Nullam at er",
		"os vel lacus maximus tempor. Nulla erat turpis, tincidunt scelerisque semper ac, tincidunt ullamcorper mi.",
	}, { // 8 Bits
		"Incidunt maló meminit multi perpetiuntur perpetuam poténti probarent sapientiam tradere. Bonorum civium comprehensam consiliisque divi",
		"num, doctrina factórum inducitur intellegunt ostendis sánciret torqueántur universas vénissét. Adversa aut conférébamus cotidie disput",
		"ari, hae horum luptatum omittam quale transféram. ",
	}, { // 16 Bits
		"害告オサ青年りやっき替虐ぞ位負ニムクヌ学事価いざせ第65事ゆぼほリ宣回めだうも映拉替ッぶげら福81常評像林すこぴふ。的ヲ講落雨協もず族",
		"載ワエノチ退面ラクう略注キイモケ断村エウマコ択者キツ安芙索セ口照行テロワ政周いフ測感セユ開営亡べ。嵐レ紙4探レイマ転96映不ゃう阜不ご",
		"ク攻移けだ口認ク政内びらいし稿葉ばょリゃ棋聞込テル害浴レリ果静び真大歳喚おぱ。",
	}, { // UTF-16
		"🌆🐤💎🐑🐩 🌾👽🐂🎂 💾🏊👳🌛 🎠👠🐇🎮 🎰🍔🐣📁 🔠👞📒🍗 👧👖👓🐁🍀",
		"🕢📦🕧📳💅🐲🎍🎭 👽💥🐆🍕🍦🕣🐤 👄💦🕘🐾🌌👰 🌹🏈🔌📊🍁 🍲📥💱🌗 🎇",
		"💸🌸📎💟🏨 💼💉🔯🎬 🐚📡🌞💶🐈",
	},
}

func TestSplit(t *testing.T) {
	limit := 134
	for _, multipart := range multipartList {
		expected := strings.Join(multipart, "")
		splitter := BestSplitter(BestCoding(expected))
		segments := splitter.Split(expected, limit)
		require.Equal(t, multipart, segments)
		for _, segment := range segments {
			require.LessOrEqual(t, splitter.Len(segment), limit)
		}
	}
}
```

this is what you want?

**Comment by itsursujit** [comment]
Yes exactly

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/95016254-6e3eef00-0684-11eb-8365-67940799de2d.png)

@itsursujit 100% test coverage of `pdu` and `data-coding`.

support auto detect best coding (gsm7bit, ascii, latin-1, cyrillic, hebrew, shift-jp, euc-kr and ucs2)

expected 11 month open source the my repo. (current is private repo)

**Comment by itsursujit** [comment]
@septs Great! Currently it's not open source?

**Comment by septs** [comment]
https://github.com/NiceLabs/go-smpp

**Comment by itsursujit** [comment]
@septs It's awesome. Thanks for this... :) I will try it out

**Comment by itsursujit** [comment]
@septs I've created two issues:
https://github.com/NiceLabs/go-smpp/issues/1
https://github.com/NiceLabs/go-smpp/issues/2
