### ISSUE TITLE
UTF-16 encoded length issue

### ISSUE THREAD

**Issue by septs** [linxGnu/gosmpp#40]
https://github.com/linxGnu/gosmpp/blob/cc603b5cc822dcd18a9d1e72b65158f773be5db5/data/codings.go#L150-L152

This a simple algorithm not correct.

e.q: Wrong for Emoji

```
>>> '😈'.encode('utf-16-be')
b'\xd8=\xde\x08'
>>> len(_)
4
```

**Comment by septs** [comment]
```go
func utf16Rune(r rune) int {
	if ((r >= 0x0000) && (r <= 0xD7FF)) || ((r >= 0xE000) && (r <= 0xFFFF)) {
		return 2
	}
	return 4
}
```

Reference: https://www.unicode.org/reports/tr26/tr26-4.html

**Comment by linxGnu** [comment]
@bachhh Could you please check this issue?
