### ISSUE TITLE
How can I get the Exception.ConnectionClosingDueToError and reconnect?

### ISSUE THREAD

**Issue by yangqi365** [linxGnu/gosmpp#5]
Hi, @linxGnu 

When the `TCPIPConnection` got [`Exception.ConnectionClosingDueToError`](https://github.com/linxGnu/gosmpp/blob/master/TCPIPConnection.go#L199)  , how can I get it in my [listener](https://github.com/linxGnu/gosmpp/blob/master/Receiver.go#L216)? I want to reconnect if `Exception.ConnectionClosingDueToError` happend.

Thanks.

**Comment by linxGnu** [comment]
Hello @yangqi365 ,

Thank you very much for your concern. To make it happened, I added hook api for your PDU Listener.

Please kindly take a look at: https://github.com/linxGnu/gosmpp/commit/388b2bc52ae431dd0c12855e899573d29127bb79

You could use this hook now by adding `HandleException(*Exception.Exception)` to your current  `ServerPDUEventListener`

I released `v0.1.3` as well.

**Comment by yangqi365** [comment]
> Hello @yangqi365 ,
> 
> Thank you very much for your concern. To make it happened, I added hook api for your PDU Listener.
> 
> Please kindly take a look at: [388b2bc](https://github.com/linxGnu/gosmpp/commit/388b2bc52ae431dd0c12855e899573d29127bb79)
> 
> You could use this hook now by adding `HandleException(*Exception.Exception)` to your current `ServerPDUEventListener`
> 
> I released `v0.1.3` as well.

It's great, thank you.
