### ISSUE TITLE
Small fix g++ and serving address

### ISSUE THREAD

**Issue by adriantabirta** [linxGnu/gosmpp#51]
**Some updates to run project** 

**1. In the _run.sh_ file**
```
g++ smsc.cpp -o smsc && ./smsc
to
g++ -std=c++11 smsc.cpp -o smsc && ./smsc
```
in my case **smsc.cpp** does not compile, have 2 errors and around 20 warnings. (macos, default installed g++)

**2. In file _main.go_ change**
```
auth := gosmpp.Auth{	
	SMSC:       "smscsim.melroselabs.com:2775", -> "localhost:2775"
        ...     
```

**3. Is it possible to write whole server in go for testing?**

**Comment by linxGnu** [comment]
@adriantabirta Thank you very much for trying gosmpp.
Yeah, I will make a fix for local testing.

For your question about writing whole server in go, I must put in much effort for that. Unfortunately, I am too busy this time. Hope someone could help me :(

**Comment by adriantabirta** [comment]
I would like to try but have no idea how SMPP works. Btw thx for nice go client (helped me alot).

**Comment by linxGnu** [comment]
:+1: Please tell me if anything wrong during your usage. I am very happy when my lib helps.

**Comment by adriantabirta** [comment]
I`m not sure that I can send messages with 160 char length. On client
```
 handlePDU()
     case *pdu.DeliverSM:
```

never receive more than 76 char, only one DeliverSM is received.

**Comment by linxGnu** [comment]
@adriantabirta It will depend on:
1. Encoding: if its 7-bit, then I think 160 char is ok
2. If not 7-bit encoding or your messages is >= 160 char, I would recommend using concatenated message instead.

@bachhh could you please provide an example of using concatenated message

**Comment by bachhh** [comment]
@adriantabirta I can explain that, length of SMS message is dictated by GSM standards, while SMPP is a standard protocol for asynchrous communication between devices / endpoints in telecom networks.
In GSM 3.38 ( which is what this project follows ), SMS messages are allowed for a maximum of 148 bytes, which is 160 ASCII character, or around 74 UNICODE characters ( 2 bytes per character ). Anything longer than that will have to be sent over multiple  PDU packets, and the receiving ends will have merge them manually.

I'll try to provide some example HTTP to SMPP server in the `example/` directory.

**Comment by adriantabirta** [comment]
Wow, would be nice. Thx

Tăbîrţă Adrian
iOS, JAVA and GO developer 
+373 60 425424
