### ISSUE TITLE
How should I handle binary messages ?

### ISSUE THREAD

**Issue by goten4** [linxGnu/gosmpp#52]
I need to handle binary messages.

It appears that the data coding of DeliverSM PDU is not exposed, and in `codingMap` (`codings.go:209)`, data coding 0x02 and 0x04 are not supported (datacoding codes for 8-bit binary).
It's the same problem for SubmitSM.

Have you ever met this issue ?
Do you intend to support binary messages in the future ?
I can make a pull request if you wish, any suggestions of implementation are welcome ;).

**Comment by linxGnu** [comment]
@goten4 thank you very much and welcome.

Could you please make a PR for exposing data coding and support missing encoder 👍
