### ISSUE TITLE
How to handle Submit_SM_Resp in Transmitter connection ?

### ISSUE THREAD

**Issue by goten4** [linxGnu/gosmpp#57]
I can't figure out how to handle the Submit_SM_Resp in a Transmitter connection.

The [SMPP specification](https://smpp.org/SMPP_v3_4_Issue1_2.pdf) (page 17) says that the Submit_SM_Resp is sent in the same connection of the transmitter, but there's no way to listen for the PDU responses in the `TransmitSettings`.

Did I miss something in the library ?

**Comment by goten4** [comment]
Another problem linked to that issue is that the receiver do not send EnquireLink.

I think it's a global issue ... You assumed that a transmitter do not receive anything, and a receiver do not send anything.

However a trasmitter can receive following PDUs :
- UNBIND
- UNBIND_RESP
- SUBMIT_SM_RESP
- SUBMIT_SM_MULTI_RESP
- DATA_SM
- DATA_SM_RESP
- QUERY_SM_RESP
- CANCEL_SM_RESP
- REPLACE_SM_RESP
- ENQUIRE_LINK
- ENQUIRE_LINK_RESP
- GENERIC_NACK

As well a receiver can send following PDUs :
- UNBIND
- UNBIND_RESP
- DATA_SM
- DATA_SM_RESP
- DELIVER_SM_RESP
- ENQUIRE_LINK
- ENQUIRE_LINK_RESP
- GENERIC_NACK

**Comment by linxGnu** [comment]
@goten4 I am very sorry for late reply due to personal issue as I told before.

Yes, you are right, this is missing spec.

I am thinking of supporting it. @bachhh HDYT

**Comment by goten4** [comment]
@linxGnu Thanks for the invitation, and no pb for the not so late reply :)

I worked on this issue with my project team because we had to go further.
I can submit a PR but you may not be ok with the choices we had to take.
It breaks compatibility. I'll explain in the PR.

**Comment by linxGnu** [comment]
@goten4 I already include a fix at #61 
I wonder if you could PTAL :+1:
