### ISSUE TITLE
can you provide an example for SMPP Receiver/Transmitter client connection?

### ISSUE THREAD

**Issue by vanipolnedi** [linxGnu/gosmpp#6]
Hi @linxGnu ,
can you please provide sample for SMPP Receiver/Transmitter client connection?. i think previously u had given in examples folder but i can't find it now. 

Thanks in advance.

**Comment by linxGnu** [comment]
Hello @vanipolnedi . Could you please refer to this issue: #4 
I believe it could help you out.

**Comment by linxGnu** [comment]
I will close this issue. Thank you for your comment.
