### ISSUE TITLE
Feature request: Rate limiter for ESME submit_sms

### ISSUE THREAD

**Issue by robertmircea** [linxGnu/gosmpp#72]
All real SMSC that I've worked with have a rate limiting policy to prevent ESME to send submit_sm too fast. If the SMSC is detecting that ESME overpasses the allowed limiting (e.g. submits/sec), it will respond with ESME_RTHROTTLED and message will not be delivered.  It would be useful if the library would support out-of-the box rate limiting the number of submits sent to SMSC.

**Comment by linxGnu** [comment]
Hello @robertmircea , thank you very much for suggesting that great feature. 

It might not be the scope of the library. However, I believe we could do something. I will discuss with @bachhh and let you know.
