### ISSUE TITLE
Any Server example with this library

### ISSUE THREAD

**Issue by sujit-baniya** [linxGnu/gosmpp#74]
Is there any Server example using this library?

**Comment by linxGnu** [comment]
@sujit-baniya `gosmpp` is client library. Not server side (SMSC) :)

**Comment by sujit-baniya** [comment]
Can you suggest some library that support server side?

**Comment by linxGnu** [comment]
I am afraid that I could not help you. I think (maybe) https://github.com/OpenSmpp/opensmpp is a good start

**Comment by tahseenjamal** [comment]
@linxGnu if you just want an SMPP Server to test then you can check out larvitsmpp

Both SMPP Client and Server is provided
