### ISSUE TITLE
Is gosmpp thread safe?

### ISSUE THREAD

**Issue by motaz** [linxGnu/gosmpp#82]
I'm wondering when I call **GetSequenceNumber**, and **Transceiver().Submit**, are they thread safe or I should use Mutext to prevent multi access to these functions?

**Comment by linxGnu** [comment]
@motaz yes gosmpp (latest) is thread-safe. You do not need mutex

**Comment by motaz** [comment]
Very good, this will reduce a lot of work from my side
I'm using v0.1.4-rc24, I will update to latest stable version
