### ISSUE TITLE
v0.1.4 isn't working with example - Results in Segmentation Fault

### ISSUE THREAD

**Issue by DandyDeveloper** [linxGnu/gosmpp#84]
I suspect this is because the example was built for 0.1.3 in mind. 

0.1.4-rc29 gives an immediate segfault on session closure (possibly an uncaptured error):

```
2022/06/23 10:44:16 EOF
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x4df8a0]

goroutine 19 [running]:
github.com/linxGnu/gosmpp.(*Session).Close(...)
        /home/aaron/go/pkg/mod/github.com/linx!gnu/gosmpp@v0.1.4-rc29/session.go:93
main.sendingAndReceiveSMS.func5()
        tools/smpp-client/main.go:65 +0x20
panic({0x4f4460, 0x5e5e40})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/linxGnu/gosmpp.(*Session).bound(...)
        /home/aaron/go/pkg/mod/github.com/linx!gnu/gosmpp@v0.1.4-rc29/session.go:72
github.com/linxGnu/gosmpp.(*Session).Transceiver(...)
        /home/aaron/go/pkg/mod/github.com/linx!gnu/gosmpp@v0.1.4-rc29/session.go:88
main.sendingAndReceiveSMS(0x0?)
        tools/smpp-client/main.go:71 +0x3da
created by main.main
        tools/smpp-client/main.go:20 +0x76
```

Looks as though the session state isn't instantiated as the code is breaking here: https://github.com/linxGnu/gosmpp/blob/master/session.go#L90-L96

**Comment by DandyDeveloper** [comment]
Nevermind, actually looks like the example was built for 0.1.4, so, there's just something else broken or perhaps something in my SMSC configuration that the library isn't happy with? 

Would appreciate if anyone has any ideas whilst I diagnose.

**Comment by sujit-baniya** [comment]
@DandyDeveloper You should not proceed ahead if there's error on Connection. You see the error `EOF` that means it's not connected.

So you should change your code to this for testing

```go
if err != nil {
		panic(err)
	}
```

**Comment by DandyDeveloper** [comment]
@sujit-baniya Thank you, the EOF was a bit head scratching. I'll look into it. 

I would have thought the connect would give a little bit more verbose output on a failure. I'll dig a bit deeper and if I figure out what the SMSC / Client problems are, I'll report back here and close.

**Comment by DandyDeveloper** [comment]
@sujit-baniya Ah, I was sending to a TLS port, SMPP defaults aren't too happy with a TLS connection. Throwing it against the non-TLS worked a treat. Thank you. Closing.
