### ISSUE TITLE
Implementing TLS / Supporting SMPPS

### ISSUE THREAD

**Issue by DandyDeveloper** [linxGnu/gosmpp#85]
I see by default we use a non-TLS dialer, which in turn relies on `net.Conn` for instantiating and subsequently defining a significant portion of the downstream buffer reads/etc. 

Is there a working example or any plans to support a crypto/tls Dialer? 

I've attempted to do this myself, but I'm getting some odd PDU related errors which I'm in the process of trying to debug. 

It seems a significant portion of the libraries depend on the root connection working from the `net.Conn` return type. Has anyone had successful forks of implementing the above?

**Comment by linxGnu** [comment]
@DandyDeveloper could you share your source code. Currently, the library let you inject your own dialer while initialize connector.

```go
func TXConnector(dialer Dialer, auth Auth) Connector
```

```go
// Dialer is connection dialer.
type Dialer func(addr string) (net.Conn, error)
```

I believe there is nothing block you from TLS Conn

**Comment by DandyDeveloper** [comment]
@linxGnu Great point, I missed that this was a public function. Let me use that.
