### ISSUE TITLE
SetLongMessageWith Encoding works not correct

### ISSUE THREAD

**Issue by aganemnam** [linxGnu/gosmpp#89]
Hi All. 
In version 1.4.0+ cant send a long messages.

func newSubmitSM() *pdu.SubmitSM {
	// build up submitSM
	srcAddr := pdu.NewAddress()
	srcAddr.SetTon(5)
	srcAddr.SetNpi(0)
	_ = srcAddr.SetAddress("xxx-xxx-xx")
	destAddr := pdu.NewAddress()
	destAddr.SetTon(1)
	destAddr.SetNpi(1)
	_ = destAddr.SetAddress("xxx-xxx-xx")
	//submitSM := pdu.NewLongMessage().(*pdu.SubmitSM)
	submitSM := pdu.NewSubmitSM().(*pdu.SubmitSM)
	submitSM.SourceAddr = srcAddr
	submitSM.DestAddr = destAddr
	_ = submitSM.Message.SetLongMessageWithEnc("Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text eve the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not on	e centuries, but also the leap into electronic typesetting, remaining essentially unchanged.", data.UCS2)
	submitSM.ProtocolID = 0
	submitSM.RegisteredDelivery = 1
	submitSM.ReplaceIfPresentFlag = 0
	submitSM.EsmClass = 0
	return submitSM
}

sends an empty message.  Cant Send a sms messages with more than 160 symbols.
![0-02-03-a1699370658df752053de266495cd31e2f22ca4906e459625e1b28a02d136e44_57d8b3537005ab6a](https://user-images.githubusercontent.com/4993241/201672378-9b58ae0e-d676-46f8-a26f-53f8edef4b79.jpg)

**Comment by aganemnam** [comment]
No issue  ?

**Comment by aganemnam** [comment]
@linxGnu @linhduonggnu @linhduonggnu need your help.
Is it posible to fix Long messages ? 
Using Payload for example

**Comment by linxGnu** [comment]
hi @aganemnam 

You need to implement concatenated message by yourself. See also: https://en.m.wikipedia.org/wiki/Concatenated_SMS
